-- Add captainName to teams
ALTER TABLE "teams" ADD COLUMN IF NOT EXISTS "captainName" TEXT NOT NULL DEFAULT '';

-- Add password to users
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "password" TEXT NOT NULL DEFAULT '';

-- Add READY to TeamStatus enum
ALTER TYPE "TeamStatus" ADD VALUE IF NOT EXISTS 'READY';

-- Add PENDING_APPROVAL to TeamStatus enum
ALTER TYPE "TeamStatus" ADD VALUE IF NOT EXISTS 'PENDING_APPROVAL';

-- Add PENDING_APPROVAL to PoolStatus enum
ALTER TYPE "PoolStatus" ADD VALUE IF NOT EXISTS 'PENDING_APPROVAL';

-- Add new UserRole values
DO $$ BEGIN ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'GUEST'; EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Add new AuditAction values
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'APPROVE_TEAM';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'REJECT_TEAM';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'APPROVE_INDIVIDUAL';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'REJECT_INDIVIDUAL';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'CREATE_CAPTAIN';
